### PR TITLE
Collision bug

### PR DESCRIPTION
**Pull request by nitaku**
That hideous collision bug seems to be solved, thanks to a workaround. Unfortunately, this method does not work with certain shapes, but we'll think again about it if needed.

Needs testing.

### CODE REVIEW

**Comment by salvob41** [comment]
What was the workaround?

**Comment by nitaku** [comment]
The workaround consists in overlapping the collision shapes.

**Comment by salvob41** [comment]
cool, let's merge

**Comment by salvob41** [comment]
closes #72

**Pull request merged**
