### PR TITLE
Improvement Physics - physics-based grid

### PR DESCRIPTION
**Pull request by salvob41**

### CODE REVIEW

**Comment by salvob41** [comment]
This branch, in order to achieve an arcade grid that moves with physics - similar to the one used in Geometry wars, has huge performance issues. We'll try to improve that before merging.

**Comment by Calinou** [comment]
`draw_line()` calls are currently relatively expensive (this will likely change with the Vulkan renderer, which is coming in Godot 4.0).

You may also want to [rely on servers directly](https://docs.godotengine.org/en/latest/tutorials/optimization/using_servers.html) to avoid the node system's overhead.

**Comment by salvob41** [comment]
I come up with these two articles that might be useful: 

https://gamedev.stackexchange.com/questions/11342/how-do-i-replicate-the-warp-effect-from-geometry-wars
https://forum.unity.com/threads/vector-grid-geometry-wars-style-fluid-mesh-system.224952/

**Comment by salvob41** [comment]
In this PR you can check the scene:
`godot/combat/levels/conquest/2players.tscn`

In which you can find a scene with the grid. Just click on "Play Scene" and try it out

**Pull request merged**
