### PR TITLE
Refactoring Species reference

### PR DESCRIPTION
**Pull request by salvob41**
Addresses #122

### CODE REVIEW

**Comment by salvob41** [comment]
Available and ordered_species need to keep the reference to the species. 
Right now they keep the reference to a String. But we need enums or int as id for the species

**Comment by salvob41** [comment]
This is getting harder than I thought...

**Comment by salvob41** [comment]
This is ready to go, I still have some perplexity on name of assets. But we will talk later about this, @nitaku

**Comment by nitaku** [comment]
Ok, let's talk about this IRL

**Pull request merged**
